### ISSUE TITLE
Might be a useful rename ..

### ISSUE THREAD

**Issue by OneOfEleven** [DualTachyon/radtel-rt-890-oefw#10]
In bk4819.c, you could rename **BK4819_EnableFFSK1200** to something like **BK4819_Enable_MDC1200_FFSK_RX** (or such like) as it's enabling the FFSK modem specifically for mdc1200.

**Comment by DualTachyon** [comment]
Is it a standard MDC1200 setup? I remember @tunas1337 saying it wasn't quite (but I could be remembering wrong).

**Comment by OneOfEleven** [comment]
Well it's setting it specifically for a set packet size (16 bytes) 1200/1800 tones.

If you made the packet size register adjustable it could be used for general FSK, but as is it will only work with mdc1200 sized packets.

**Comment by DualTachyon** [comment]
OK
