### ISSUE TITLE
Frequency detector various gitches.

### ISSUE THREAD

**Issue by ea7hjb** [DualTachyon/radtel-rt-890-oefw#12]
Hello,

I detected various gitches on the Frequency hunter function. They happen when a frequency has been found, and they don't ocurr in the original 1.34, nor 1.33 and newest 1.35:

When the frequency has been detected and locked on, in the original firmware you could press the RED button to "reset" te process han start searching again. This doesn't happen in the OEFW.

Also, when the frequency has been detected and locked on, pressing the # button (to switch search band) doesn't work properly too. It will switch the Text to VHF, but does nothing.

If scanning the subtone (via * button), it will do weird things too when trying to going back from that function.

Thank you and best regards.

**Comment by ea7hjb** [comment]
This is the OEFW:

https://github.com/DualTachyon/radtel-rt-890-oefw/assets/17039268/e8e341f8-cf04-4a15-bc61-e29ffc5ef8e6

This is the original 1.34:


https://github.com/DualTachyon/radtel-rt-890-oefw/assets/17039268/e926f6fa-91d7-4883-8e89-334bf067f45d


Note that in the original 1.34 video when I press the red buttons it may looks like the process is not restarted, but yes, it restarts, I assure you. Only thing is that I have a small MMDVM on there emitting almost contantly so it insta-finds the frequency.

**Comment by DualTachyon** [comment]
I don't have my environment and radio with me. Try the following:

https://github.com/DualTachyon/radtel-rt-890-oefw/blob/main/radio/detector.c#L329

There are 3 "continue" statements. Change all 3 to "break". See if it works the way you expect.

If it works, a further fix is needed because the "break" will call the CdcssScan a few lines below but shouldn't. I'll check it later.

**Comment by ea7hjb** [comment]
Hi,

I'm finally back home and tested your new build. It seems like the Red Exit button and the # button works now like the original firmware :)

Thank you!
