### ISSUE TITLE
Frequency detector detects DCS at 23bits code.

### ISSUE THREAD

**Issue by ea7hjb** [DualTachyon/radtel-rt-890-oefw#13]
Hello,

As you will certainly be aware of, the RT-890 supports some short of custom CTCSS/DCS subtone that they call "23/24 bits" (I'm planning to check if this really works with some pro gear I have, but I don't know when that will be possible as I lost the programming cable). Meanwhile, I found that when using the Frequency Detector if the transmitter uses DCS it will ALWAYS detect the code as 23bit, even if it's a standard code (normal or inverted, doesn't matter). This happens in both the Freq. Hunter and the Subtone Hunter (* button).

Original FW:
![photo_2023-12-19_19-29-46](https://github.com/DualTachyon/radtel-rt-890-oefw/assets/17039268/2b799ff0-0907-496d-8f26-5f7211023c00)

OEFW:
![photo_2023-12-19_19-29-46 (2)](https://github.com/DualTachyon/radtel-rt-890-oefw/assets/17039268/7cdc2042-197d-479d-b8de-b90900634977)

Tested vs many HTs (VX-2, VX7, Quansheng, etc...) with same result, so we can discard a problem on the transmitter.

**Comment by DualTachyon** [comment]
Fixed.
