### ISSUE TITLE
ooooo

### ISSUE THREAD

**Issue by OneOfEleven** [DualTachyon/radtel-rt-890-oefw#3]
New firmware !

How does the radio sound on AM I wonder ?

**Comment by OneOfEleven** [comment]
Yes I'm fine, just had to stop people getting the latest updates as I've broken the eeprom write routine - my calibration area is now all '0's lol

I have backs of my eeproms, just trying to work out how to get the calibration area back into the radio ;)

**Comment by OneOfEleven** [comment]
Anyone who used my latest upload may have wiped their calibration data .. eeekk

They will have to use one of ours if they didn't make a backup of their radios calibration data

**Comment by OneOfEleven** [comment]
The last good commit was 72f3fd8 .. I think, anything after is when I was fixing a serial comms problem

**Comment by OneOfEleven** [comment]
I can't see anywhere that prevents uploading data to the calibration area, so I'm uploading my data back to there but when I read it back it shows all '0's

**Comment by OneOfEleven** [comment]
Tell them NOT to upload any config settings, ie channels etc, they will be safe if they don't upload new channels etc.

**Comment by OneOfEleven** [comment]
They can read it all OK, and I'd say if they can then save a backup of their eeprom areas whilst it's intact.

**Comment by OneOfEleven** [comment]
Darn it, can't write to the eeprom :(  it's all zeros. I guess the bootloader is stopping to firmware doing anymore writes.

**Comment by OneOfEleven** [comment]
> What tools have you tried?

Just my own firmware/eeprom k5prog software

**Comment by OneOfEleven** [comment]
Yes I've tried the QS firmwares, also yours, but none will write any new config uploads to eeprom.

They let let me upload to apparent eeprom, but the radios memories and settings remain defaults.

tried the factory reset in the menu using the different firmwares as well, but nothing alters the eeprom contents.

**Comment by OneOfEleven** [comment]
I've added the original calibration data for the radio into our firmware as a 512-byte const array and try to write that directly to the calibration area 0E00 to 0X0FFF but no luck, the area still reads back as all zeros.

**Comment by OneOfEleven** [comment]
Something is preventing write access to the eeprom.

**Comment by OneOfEleven** [comment]
This is the little function I've written to try to restore my backed up original calibration data ..

```
const uint8_t calib2[] =
{
	0x0A, 0x4B, 0x53, 0x56, 0x59, 0x5C, 0x5F, 0x62, 0x64, 0x66, 0xFF, 0xFF,
	0xFF, 0xFF, 0xFF, 0xFF, 0x05, 0x46, 0x50, 0x53, 0x56, 0x59, 0x5C, 0x5F,
	0x62, 0x64, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x5A, 0x2D, 0x29, 0x26,
	0x23, 0x20, 0x1D, 0x1A, 0x17, 0x14, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
	0x64, 0x30, 0x2D, 0x29, 0x26, 0x23, 0x20, 0x1D, 0x1A, 0x17, 0xFF, 0xFF,
	0xFF, 0xFF, 0xFF, 0xFF, 0x5A, 0x14, 0x11, 0x0E, 0x0B, 0x08, 0x03, 0x02,
	0x02, 0x02, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x64, 0x11, 0x0E, 0x0B,
	0x08, 0x05, 0x05, 0x04, 0x04, 0x04, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
	0x32, 0x68, 0x6B, 0x6E, 0x6F, 0x72, 0x75, 0x77, 0x79, 0x7B, 0xFF, 0xFF,
	0xFF, 0xFF, 0xFF, 0xFF, 0x28, 0x64, 0x67, 0x6A, 0x6C, 0x6E, 0x71, 0x73,
	0x76, 0x78, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x41, 0x32, 0x2D, 0x28,
	0x24, 0x21, 0x1E, 0x1A, 0x17, 0x16, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
	0x46, 0x37, 0x32, 0x2D, 0x28, 0x25, 0x22, 0x1E, 0x1B, 0x19, 0xFF, 0xFF,
	0xFF, 0xFF, 0xFF, 0xFF, 0x5A, 0x19, 0x0F, 0x0A, 0x09, 0x08, 0x07, 0x06,
	0x05, 0x04, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x64, 0x1E, 0x14, 0x0F,
	0x0D, 0x0C, 0x0B, 0x0A, 0x09, 0x08, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
	0x6E, 0x00, 0x78, 0x00, 0x82, 0x00, 0x8C, 0x00, 0x86, 0x00, 0xAA, 0x00,
	0xCE, 0x00, 0xF2, 0x00, 0x32, 0x32, 0x32, 0x64, 0x64, 0x64, 0x8C, 0x8C,
	0x8C, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x32, 0x32, 0x32, 0x64,
	0x64, 0x64, 0x8C, 0x8C, 0x8C, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
	0x5F, 0x5F, 0x5F, 0x69, 0x69, 0x69, 0x7B, 0x7D, 0x7F, 0xFF, 0xFF, 0xFF,
	0xFF, 0xFF, 0xFF, 0xFF, 0x32, 0x32, 0x32, 0x64, 0x64, 0x64, 0x8C, 0x8C,
	0x8C, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x5A, 0x5A, 0x5A, 0x64,
	0x64, 0x64, 0x82, 0x82, 0x82, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
	0x5A, 0x5A, 0x5A, 0x64, 0x64, 0x64, 0x8B, 0x8D, 0x8A, 0xFF, 0xFF, 0xFF,
	0xFF, 0xFF, 0xFF, 0xFF, 0x32, 0x32, 0x32, 0x64, 0x64, 0x64, 0x8C, 0x8C,
	0x8C, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xEE, 0x04, 0x10, 0x07,
	0x5A, 0x07, 0x73, 0x07, 0xD9, 0x07, 0xFC, 0x08, 0xFF, 0xFF, 0xFF, 0xFF,
	0x1E, 0x00, 0x32, 0x00, 0x46, 0x00, 0x5A, 0x00, 0x6E, 0x00, 0x82, 0x00,
	0x96, 0x00, 0xAA, 0x00, 0xC8, 0x00, 0xE6, 0x00, 0xFF, 0xFF, 0xFF, 0xFF,
	0x14, 0x00, 0x28, 0x00, 0x3C, 0x00, 0x50, 0x00, 0x64, 0x00, 0x78, 0x00,
	0x8C, 0x00, 0xA0, 0x00, 0xBE, 0x00, 0xDC, 0x00, 0xFF, 0xFF, 0xFF, 0xFF,
	0x03, 0x08, 0x0E, 0x13, 0x18, 0xFF, 0xFF, 0xFF, 0x05, 0x00, 0x46, 0x00,
	0x50, 0x00, 0x2C, 0x0E, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
	0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
	0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
	0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
	0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
	0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
	0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
	0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
	0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
	0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF
};

void SETTINGS_restore(void)
{
	unsigned int index = 0;
	while (index < sizeof(calib2))
	{
		const unsigned int addr = 0x0E00 + index;
		if (addr < 0x0E98 || addr >= 0x0EA0)
			EEPROM_WriteBuffer(addr, &calib2[index]);
		index += 8;
	}
}
```

**Comment by OneOfEleven** [comment]
of cause it is !  see what happens when you're not thinking straight.

Still not working, eeprom still reads back as all zeros :(

**Comment by OneOfEleven** [comment]
QS CPS won't work, I tell it to read the radio but wants me to enter a password at that point.
Chirp downloads from but all data is blank.
I read the eeprom area with k5prog-win, it's all blank too.

**Comment by OneOfEleven** [comment]
I upload to radio with chirp my saves channel settings etc, it uploads but no change, radio still blank.

**Comment by OneOfEleven** [comment]
Do you know the eeproms number I wonder (I could look at the datasheet) ? .. does it have any write protect ability ?

**Comment by pawol** [comment]
@OneOfEleven Where is uv k5 repo now?

**Comment by OneOfEleven** [comment]
Still there, but I've had to disable it for now till I solve a big problem. I don't want anyone else loosing their radios.

I'll make it public again asap, don't worry.

**Comment by OneOfEleven** [comment]
I tried to delete the last few commits but github won't let me ??

**Comment by OneOfEleven** [comment]
All I'm getting now is ..

```
Cannot` push these commits as they contain an email address marked as private on GitHub. To push anyway, visit https://github.com/settings/emails, uncheck "Keep my email address private", then switch back to GitHub Desktop to push your commits. You can then enable the setting again.
```

**Comment by OneOfEleven** [comment]
There are no email address in any of the files.

**Comment by OneOfEleven** [comment]
ahh poo

**Comment by OneOfEleven** [comment]
I'm going to delete the repo then put it back from fresh I think.

**Comment by OneOfEleven** [comment]
I'm getting this now ..

```
C:\Radios\Quansheng_UV-K5\uv-k5-firmware\uv-k5-firmware-custom>git checkout 58690a70824e50ba9775d0bf84a5d7d3edaaa1af
Note: switching to '58690a70824e50ba9775d0bf84a5d7d3edaaa1af'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 58690a7 Delete app/uart.c

C:\Radios\Quansheng_UV-K5\uv-k5-firmware\uv-k5-firmware-custom>git push --force
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>


C:\Radios\Quansheng_UV-K5\uv-k5-firmware\uv-k5-firmware-custom>
```

**Comment by OneOfEleven** [comment]
Thank you for your help !! .. github ggrrr

How about now, just made it public again, any emails showing ?

**Comment by OneOfEleven** [comment]
oh right, thank you !

**Comment by OneOfEleven** [comment]
I tried Windows github desktop app earlier tonite, that's what exposed an email :(

**Comment by OneOfEleven** [comment]
my poor lil radio, and other peoples too no doubt :(

**Comment by OneOfEleven** [comment]
lol

**Comment by OneOfEleven** [comment]
I'm going to investigate the eeprom problem, I need to know why it's coming back as all zeros, and why I can't restore it's contents.

**Comment by OneOfEleven** [comment]
No the radios still in one piece, not added SWD or anything, it is (or was) as new.

It's as if a read or write protect has been enabled in the eeprom, but I don't see how. I'm just looking at the chip datasheet.

**Comment by OneOfEleven** [comment]
The exact same thing has happened to @Aquila161 as well with the same code. A strange problem.

**Comment by OneOfEleven** [comment]
mmm I know

Some chips have serial commands to do similar. It's just a thought at the moment.

**Comment by zhaoparrot** [comment]
@OneOfEleven have u figured out which part of the code broke it the first place ?
got me worry for a while when i wakeup this morning and see your activity 404
lucky i found u here and now i know whats going on .
if u need someones help testing something .let me know . i dont care if i broke my radio in the process.

**Comment by OneOfEleven** [comment]
oh right !

**Comment by OneOfEleven** [comment]
> @OneOfEleven have u figured out which part of the code broke it the first place ? got me worry for a while when i wakeup this morning and see your activity 404 lucky i found u here and now i know whats going on . if u need someones help testing something .let me know . i dont care if i broke my radio in the process.

Yes I have, I messed up the line that writes the received serial data (from the PC) to eeprom, and so wrote incorrect data to eeprom.

Thank you for your support :)  Yes shit happens unfortunately, it's part of the process.

**Comment by OneOfEleven** [comment]
In my haste to fix the problem I caused and being tired etc last night I wasn't thinking straight.
