### ISSUE TITLE
Possible miss named ?

### ISSUE THREAD

**Issue by OneOfEleven** [DualTachyon/radtel-rt-890-oefw#6]
You have a function called **BK4819_EnableAutoCssBW**, but looking at that BK register, it looks like your disabling    auto BW rather than enabling it ?

An unconnected observation ..

Interesting that quite a few unknown registers are being set in the BK init routine. If only we had a proper full datasheet on the chip.

**Comment by OneOfEleven** [comment]
oo thank you for the pin names :)

The original comment was for the 890.

**Comment by DualTachyon** [comment]
When checking the new docs you received, don't pay too much attention to the GPIO numbering... It seems the ordering is reversed from the old docs. In practice, nothing changes, bit 0 of register 0x33/etc is still the same physical pin.
Based on the decompilation of K5, the old naming we have used is the correct because the GPIO function uses 0x40 >> pin number (BK4819_GPIO_PIN0 -> 0x40, PIN1 -> 0x20, ...).

I wonder if going between BK4819 v1 and v3 spins they fixed the ordering (coz bit 0 being GPIO6 is visually odd).

**Comment by OneOfEleven** [comment]
Okey doke, sounds good. You obviously are using the pins for what they are connected for, so doesn't matter what they call what pin in there PDF's etc, I wasn't going to change anything there.

Not actually much more info in the data sheets than what we already had really, a couple of unknown registers are listed which is good to know. bit not many really.

Still nice to have the proper doc's.

They say they supply more info to the manufactures/designers about the chip for customizing things. Don't know why they don't just publish ALL the chip details really, it's for there benefit afterall.

**Comment by OneOfEleven** [comment]
I see some  others are taking all the credit for your work :(

**Comment by DualTachyon** [comment]
Where?

**Comment by OneOfEleven** [comment]
Various places I think

**Comment by DualTachyon** [comment]
What happened? Seems all your repos are now gone...

**Comment by zhaoparrot** [comment]
> What happened? Seems all your repos are now gone...

![image](https://github.com/DualTachyon/radtel-rt-890-oefw/assets/27049669/d85de51b-6bef-47a0-b0a0-71971994ec8c)
also my fork of 1o11's code now pointing to a wrong upsteam, dont know how to change it back .googleing...

**Comment by DualTachyon** [comment]
It seems there's an incorrect tone 1 in your DTMF code. "tone1 = 679" that should be "tone1 = 697".

![image](https://github.com/DualTachyon/radtel-rt-890-oefw/assets/4077499/9ee9631b-22ca-4847-92ca-4a69f378890a)

**Comment by DualTachyon** [comment]
In your pan files, you added your username but put my GH link instead of yours.
