### ISSUE TITLE
ui/helper.c error

### ISSUE THREAD

**Issue by M7OCM** [DualTachyon/radtel-rt-890-oefw#9]
Yo UP how are you, just tweaking colours and noticed the bell icon jumps a pixel. Photo explaination.

![20231024_104323](https://github.com/DualTachyon/radtel-rt-890-oefw/assets/128899149/e1300939-9563-4b7b-bd7e-956e08041006)

Thank you for OEFW!!!

**Comment by DualTachyon** [comment]
It's not an OEFW bug. The original has the same issue according to Ghidra. It only affects the "clearing" of the "1" / "2" rendering.

**Comment by M7OCM** [comment]
> It's not an OEFW bug. The original has the same issue according to Ghidra. It only affects the "clearing" of the "1" / "2" rendering.

Copy that!
